# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Thesis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QMessageBox, QInputDialog, QApplication, QWidget, QLineEdit, QFileDialog, QSizeGrip, QSlider
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon
import os

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, name_mesh=None, name_cage=None, path_mesh=[], path_cage=None,
                status_data_cage=None, parts_array = [], flip_mesh = None, list_text = [], iter_subdiv = None, def_vol = [],
                 status_gtime=False, status_gmeth=False, status_gloc=False, status_gpetro = False, flip_calcint = None):
        self.path_mesh = path_mesh
        self.name_mesh = name_mesh
        self.path_cage = path_cage
        self.name_cage = name_cage
        self.status_data_cage = status_data_cage
        self.part = parts_array
        self.flip_mesh = flip_mesh
        self.list_text = list_text
        self.iter_subdiv = iter_subdiv
        self.def_vol = def_vol
        self.status_GeoTime = status_gtime
        self.status_GeoPetro = status_gpetro
        self.status_GeoMeth = status_gmeth
        self.status_GeoLoc = status_gloc
        self.flip_calcint = flip_calcint

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(751, 424)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(751, 373))
        MainWindow.setMaximumSize(QtCore.QSize(751, 424))
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(751, 373))
        self.centralwidget.setMaximumSize(QtCore.QSize(751, 373))
        self.centralwidget.setStyleSheet("*{\n"
"    color: #000;\n"
"    border: none\n"
"}\n"
"\n"
"#leftMenu{\n"
"    background-color: #2596be;\n"
"}\n"
"\n"
"#mainBody{\n"
"    background-color: #eeeee4;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background: transparent;\n"
"    border: 2px solid #2596be;\n"
"    color: #2596be;\n"
"}\n"
" \n"
"#appHeader{\n"
"    color: #2596be;\n"
"}\n"
"\n"
"#butLabelAssign{\n"
"    background-color: #2596be;\n"
"    color: #fff;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#butLabelsStatus{\n"
"    background-color: #2596be;\n"
"    color: #fff;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#butEntities{\n"
"    background-color: #2596be;\n"
"    color: #fff;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#butCancel{\n"
"    background-color: #000000;\n"
"    color: #fff;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#butSubmit{\n"
"    background-color: #000000;\n"
"    color: #fff;\n"
"    border-radius: 3px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.mainBody = QtWidgets.QWidget(self.centralwidget)
        self.mainBody.setGeometry(QtCore.QRect(0, 0, 751, 373))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBody.sizePolicy().hasHeightForWidth())
        self.mainBody.setSizePolicy(sizePolicy)
        self.mainBody.setMinimumSize(QtCore.QSize(751, 373))
        self.mainBody.setMaximumSize(QtCore.QSize(751, 373))
        self.mainBody.setStyleSheet("#mainBody{\n"
"    background-color: #eeeee4;\n"
"}")
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QWidget(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerFrame.sizePolicy().hasHeightForWidth())
        self.headerFrame.setSizePolicy(sizePolicy)
        self.headerFrame.setMinimumSize(QtCore.QSize(736, 65))
        self.headerFrame.setMaximumSize(QtCore.QSize(1000, 65))
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.headerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menuBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBtn.sizePolicy().hasHeightForWidth())
        self.menuBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menuBtn.setFont(font)
        self.menuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/blueocean_icons/icons/blue_ocean/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon)
        self.menuBtn.setIconSize(QtCore.QSize(32, 32))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_5.addWidget(self.menuBtn)
        self.appHeader = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appHeader.sizePolicy().hasHeightForWidth())
        self.appHeader.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.appHeader.setFont(font)
        self.appHeader.setObjectName("appHeader")
        self.horizontalLayout_5.addWidget(self.appHeader)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignLeft)
        self.widget_17 = QtWidgets.QWidget(self.headerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelFeedText = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFeedText.setFont(font)
        self.labelFeedText.setObjectName("labelFeedText")
        self.horizontalLayout_7.addWidget(self.labelFeedText)
        self.horizontalLayout.addWidget(self.widget_17)
        self.widget_3 = QtWidgets.QWidget(self.headerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_3.setSizeIncrement(QtCore.QSize(50, 0))
        self.widget_3.setBaseSize(QtCore.QSize(50, 0))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(30, 30))
        self.label_9.setMaximumSize(QtCore.QSize(30, 30))
        self.label_9.setSizeIncrement(QtCore.QSize(30, 30))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/blueocean_icons/icons/blue_ocean/file-text.svg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.frame_6 = QtWidgets.QFrame(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(110, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(110, 16777215))
        self.frame_6.setSizeIncrement(QtCore.QSize(80, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setContentsMargins(-1, 1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.statusData = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusData.sizePolicy().hasHeightForWidth())
        self.statusData.setSizePolicy(sizePolicy)
        self.statusData.setMinimumSize(QtCore.QSize(100, 14))
        self.statusData.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.statusData.setFont(font)
        self.statusData.setObjectName("statusData")
        self.verticalLayout_9.addWidget(self.statusData)
        self.butLabelsStatus = QtWidgets.QPushButton(self.frame_6)
        self.butLabelsStatus.setMinimumSize(QtCore.QSize(95, 16))
        self.butLabelsStatus.setMaximumSize(QtCore.QSize(95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.butLabelsStatus.setFont(font)
        self.butLabelsStatus.setObjectName("butLabelsStatus")
        self.verticalLayout_9.addWidget(self.butLabelsStatus)
        self.butEntities = QtWidgets.QPushButton(self.frame_6)
        self.butEntities.setMinimumSize(QtCore.QSize(95, 16))
        self.butEntities.setMaximumSize(QtCore.QSize(95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.butEntities.setFont(font)
        self.butEntities.setObjectName("butEntities")
        self.verticalLayout_9.addWidget(self.butEntities)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.widget_3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.headerFrame, 0, QtCore.Qt.AlignLeft)
        self.cardsFrame = QtWidgets.QWidget(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(250)
        sizePolicy.setHeightForWidth(self.cardsFrame.sizePolicy().hasHeightForWidth())
        self.cardsFrame.setSizePolicy(sizePolicy)
        self.cardsFrame.setMinimumSize(QtCore.QSize(746, 240))
        self.cardsFrame.setMaximumSize(QtCore.QSize(746, 240))
        self.cardsFrame.setSizeIncrement(QtCore.QSize(0, 250))
        self.cardsFrame.setBaseSize(QtCore.QSize(0, 250))
        self.cardsFrame.setObjectName("cardsFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cardsFrame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.cardsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(250)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(267, 250))
        self.widget_6.setMaximumSize(QtCore.QSize(746, 250))
        self.widget_6.setSizeIncrement(QtCore.QSize(0, 250))
        self.widget_6.setBaseSize(QtCore.QSize(0, 250))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameCrease = QtWidgets.QFrame(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCrease.sizePolicy().hasHeightForWidth())
        self.frameCrease.setSizePolicy(sizePolicy)
        self.frameCrease.setMinimumSize(QtCore.QSize(245, 210))
        self.frameCrease.setMaximumSize(QtCore.QSize(746, 210))
        self.frameCrease.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCrease.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCrease.setObjectName("frameCrease")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameCrease)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.frameCrease)
        self.widget_5.setMinimumSize(QtCore.QSize(745, 50))
        self.widget_5.setMaximumSize(QtCore.QSize(745, 50))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.butLabelAssign = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butLabelAssign.sizePolicy().hasHeightForWidth())
        self.butLabelAssign.setSizePolicy(sizePolicy)
        self.butLabelAssign.setMinimumSize(QtCore.QSize(240, 27))
        self.butLabelAssign.setMaximumSize(QtCore.QSize(240, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.butLabelAssign.setFont(font)
        self.butLabelAssign.setAutoFillBackground(False)
        self.butLabelAssign.setObjectName("butLabelAssign")
        self.horizontalLayout_6.addWidget(self.butLabelAssign)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.widget_28 = QtWidgets.QWidget(self.frameCrease)
        self.widget_28.setMinimumSize(QtCore.QSize(241, 28))
        self.widget_28.setMaximumSize(QtCore.QSize(745, 28))
        self.widget_28.setObjectName("widget_28")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_28)
        self.horizontalLayout_12.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(50)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkGeoMeth = QtWidgets.QCheckBox(self.widget_28)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkGeoMeth.setFont(font)
        self.checkGeoMeth.setObjectName("checkGeoMeth")
        self.horizontalLayout_12.addWidget(self.checkGeoMeth, 0, QtCore.Qt.AlignHCenter)
        self.checkGeoLoc = QtWidgets.QCheckBox(self.widget_28)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkGeoLoc.setFont(font)
        self.checkGeoLoc.setObjectName("checkGeoLoc")
        self.horizontalLayout_12.addWidget(self.checkGeoLoc)
        self.checkGeoPetro = QtWidgets.QCheckBox(self.widget_28)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkGeoPetro.setFont(font)
        self.checkGeoPetro.setObjectName("checkGeoPetro")
        self.horizontalLayout_12.addWidget(self.checkGeoPetro)
        self.checkGeoTime = QtWidgets.QCheckBox(self.widget_28)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkGeoTime.setFont(font)
        self.checkGeoTime.setObjectName("checkGeoTime")
        self.horizontalLayout_12.addWidget(self.checkGeoTime, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.widget_28, 0, QtCore.Qt.AlignHCenter)
        self.widget_2 = QtWidgets.QWidget(self.frameCrease)
        self.widget_2.setMinimumSize(QtCore.QSize(241, 28))
        self.widget_2.setMaximumSize(QtCore.QSize(746, 56))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelInputWord = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInputWord.sizePolicy().hasHeightForWidth())
        self.labelInputWord.setSizePolicy(sizePolicy)
        self.labelInputWord.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelInputWord.setFont(font)
        self.labelInputWord.setObjectName("labelInputWord")
        self.horizontalLayout_2.addWidget(self.labelInputWord)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(500, 19))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(500, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_2.addWidget(self.lineEdit_20)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.widget_8 = QtWidgets.QWidget(self.frameCrease)
        self.widget_8.setMinimumSize(QtCore.QSize(745, 50))
        self.widget_8.setMaximumSize(QtCore.QSize(745, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget_8.setFont(font)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.butCancel = QtWidgets.QPushButton(self.widget_8)
        self.butCancel.setMinimumSize(QtCore.QSize(110, 30))
        self.butCancel.setMaximumSize(QtCore.QSize(110, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.butCancel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.butCancel.setFont(font)
        self.butCancel.setObjectName("butCancel")
        self.horizontalLayout_8.addWidget(self.butCancel)
        self.butSubmit = QtWidgets.QPushButton(self.widget_8)
        self.butSubmit.setMinimumSize(QtCore.QSize(110, 30))
        self.butSubmit.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.butSubmit.setFont(font)
        self.butSubmit.setObjectName("butSubmit")
        self.horizontalLayout_8.addWidget(self.butSubmit)
        self.verticalLayout_5.addWidget(self.widget_8)
        self.verticalLayout_4.addWidget(self.frameCrease)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.verticalLayout.addWidget(self.cardsFrame, 0, QtCore.Qt.AlignLeft)
        self.widget_7 = QtWidgets.QWidget(self.mainBody)
        self.widget_7.setMinimumSize(QtCore.QSize(670, 30))
        self.widget_7.setMaximumSize(QtCore.QSize(738, 30))
        self.widget_7.setObjectName("widget_7")
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setGeometry(QtCore.QRect(0, 2, 330, 30))
        self.label_10.setMinimumSize(QtCore.QSize(330, 30))
        self.label_10.setMaximumSize(QtCore.QSize(330, 31))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.widget_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #MULTI FILE BUTTON
        self.butEntities.clicked.connect(self.data_input_text)

        #BUTTON LABEL
        self.checkGeoLoc.toggled.connect(lambda: self.param_boxbound())
        self.checkGeoMeth.toggled.connect(lambda: self.param_calcint())
        self.checkGeoPetro.toggled.connect(lambda: self.param_simpsubd())
        self.checkGeoTime.toggled.connect(lambda: self.param_simpsubd())

        #BUTTON
        self.butSubmit.clicked.connect(self.vis_mesh)
        self.butCancel.clicked.connect(self.vis_mesh)
        self.butLabelsStatus.clicked.connect(self.vis_mesh)
        self.butLabelAssign.clicked.connect(self.vis_mesh)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appHeader.setText(_translate("MainWindow", "GeoBERT"))
        self.labelFeedText.setText(_translate("MainWindow", "TextLabel"))
        self.statusData.setText(_translate("MainWindow", "Recorded Data"))
        self.butLabelsStatus.setText(_translate("MainWindow", "Labels"))
        self.butEntities.setText(_translate("MainWindow", "Input File"))
        self.butLabelAssign.setText(_translate("MainWindow", "Next Assignment"))
        self.checkGeoMeth.setText(_translate("MainWindow", "GeoMeth"))
        self.checkGeoLoc.setText(_translate("MainWindow", "GeoLoc"))
        self.checkGeoPetro.setText(_translate("MainWindow", "GeoPetro"))
        self.checkGeoTime.setText(_translate("MainWindow", "GeoTime"))
        self.labelInputWord.setText(_translate("MainWindow", "Input Word"))
        self.butCancel.setText(_translate("MainWindow", "Cancel"))
        self.butSubmit.setText(_translate("MainWindow", "Submit"))
        self.label_10.setText(_translate("MainWindow", "by: Andika, R.B., Chudallam N., Wellmann, F. (2022)"))
# import resources_rc

    #INPUT TEXT FILE
    def data_input_text(self):
            self.open_dialog_box_cage()

    def open_dialog_box_cage(self):
            try:
                    filename = QFileDialog.getOpenFileName()
                    a = str(filename[0])
                    with open(a, 'r', encoding='utf-8') as f:
                            lines = f.read()
                    c = lines.split('\n')
                    for i in c:
                            self.list_text.append(i)


            except:
                    pass
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
